---
ID: "69f7b57d-b812-47d6-a931-924fcfc0109d"
Parent: "f38ac661-fe5c-4523-ae08-4b3edc57ae72"
Template: "f38ac661-fe5c-4523-ae08-4b3edc57ae72"
Path: /sitecore/templates/Foundation/Tracker/Tracker Settings Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{E144AAC6-7B4D-4352-80CD-F097F427E667}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T060136Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ajoshi
