---
ID: "2fbbdd7e-7401-47b6-87b0-1da596b996eb"
Parent: "a907a63e-26cc-4b1e-a40a-60d0986f8caa"
Template: "a907a63e-26cc-4b1e-a40a-60d0986f8caa"
Path: /sitecore/templates/Foundation/Tracker/_TrackerSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T050819Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ajoshi
