---
ID: "73f5a567-c08f-4aee-9a9f-8d446bfd7721"
Parent: "a907a63e-26cc-4b1e-a40a-60d0986f8caa"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Tracker/_TrackerSettings/Tracker Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T050808Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ajoshi
